import * as fs from "fs";
import { promises as fsp } from "fs";
import * as path from "path";
import * as yaml from "js-yaml";

/**
 * mkdocs.yml carries "!!python/name:" tags that js-yaml cannot resolve. They are
 * quoted before loading, exactly like sfdx-hardis does when it reads the file.
 */
const PYTHON_TAG_RE = /!!python\/name:[\w.]+/g;

export function parseMkDocsYml(content: string): any {
  const quoted = content.replace(PYTHON_TAG_RE, (tag) => `'${tag}'`);
  return yaml.load(quoted);
}

/**
 * Zensical accepts a nav sub-menu only as a LIST of single-key mappings.
 * Documentation generated by sfdx-hardis before the fix wrote sub-menus as a
 * single mapping, which MkDocs tolerated and Zensical rejects with
 * "TypeError: Unknown nav item value type: <class 'dict'>".
 *
 * Returns the labels of the menus still written the legacy way, so the user can
 * be told which ones are affected instead of just being handed a stack trace.
 */
export function findLegacyNavMenus(mkdocsYml: any): string[] {
  const legacyMenus: string[] = [];
  const walk = (items: any) => {
    if (!Array.isArray(items)) {
      return;
    }
    for (const item of items) {
      if (!item || typeof item !== "object" || Array.isArray(item)) {
        continue;
      }
      for (const [label, target] of Object.entries(item)) {
        if (Array.isArray(target)) {
          walk(target);
        } else if (target && typeof target === "object") {
          // A mapping in target position is a sub-menu written the legacy way
          legacyMenus.push(label);
        }
      }
    }
  };
  walk(mkdocsYml?.nav);
  return legacyMenus;
}

export type MkDocsCheckResult =
  | { status: "ok" }
  | { status: "missing"; mkdocsYmlFile: string }
  | { status: "unreadable"; mkdocsYmlFile: string; message: string }
  | { status: "legacyNav"; mkdocsYmlFile: string; menus: string[] };

/**
 * Pre-flight run before starting the local documentation server, so a known
 * blocking configuration is reported with a fix instead of leaving the user in
 * front of a "Starting..." notification that never completes.
 */
// Async so a large mkdocs.yml (a generated site reaches hundreds of kB) is not
// read on the extension host thread, which would freeze the UI and stop the
// progress notification from ever painting.
export async function checkMkDocsConfig(
  workspaceRoot: string,
): Promise<MkDocsCheckResult> {
  const mkdocsYmlFile = path.join(workspaceRoot, "mkdocs.yml");
  if (!fs.existsSync(mkdocsYmlFile)) {
    return { status: "missing", mkdocsYmlFile };
  }
  let mkdocsYml: any;
  try {
    mkdocsYml = parseMkDocsYml(await fsp.readFile(mkdocsYmlFile, "utf-8"));
  } catch (error: any) {
    return {
      status: "unreadable",
      mkdocsYmlFile,
      message: error?.message || String(error),
    };
  }
  const menus = findLegacyNavMenus(mkdocsYml);
  if (menus.length > 0) {
    return { status: "legacyNav", mkdocsYmlFile, menus };
  }
  return { status: "ok" };
}
