---
#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##################################################
# Start the job when a GitHub release is created #
##################################################
name: "Build & Deploy - RELEASE"
on:
  release:
    # Want to run the automation when a release is created
    types: ["created"]

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy on VsCode MarketPlace
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: release
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          package-manager-cache: false
      - run: yarn --frozen-lockfile
      - name: Publish to Visual Studio Marketplace
        run: npx vsce publish --yarn -p "$VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

  deploy_ovsx:
    name: Deploy on Open VSX
    runs-on: ubuntu-latest
    permissions:
      contents: read
    environment:
      name: release
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 22
          package-manager-cache: false
      - run: yarn --frozen-lockfile
      - name: Publish to Open VSX Registry
        run: npx --yes ovsx publish --yarn -p "$OPENVSX_TOKEN"
        env:
          OPENVSX_TOKEN: ${{ secrets.OPENVSX_TOKEN }}
